version: '3.8'

services:
  backend:
    build: ./pizzatech-backend
    ports:
      - "8000:8000"
    env_file:
      - ./pizzatech-backend/.env
    volumes:
      - ./pizzatech-backend:/app
    depends_on:
      - db

  frontend:
    build: ./pizzatech-frontend
    ports:
      - "80:80"
    volumes:
      - ./pizzatech-frontend:/app
    depends_on:
      - backend

  db:
    image: postgres:13
    env_file:
      - ./pizzatech-backend/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8091:8080"

volumes:
  postgres_data:
